

const LOADING = 'LOADING';
const TOGGLE_MODAL = 'TOGGLE_MODAL';
const UPDATE_TEAM_SETTINGS = 'UPDATE_TEAM_SETTINGS';
const PLAYERS_COUNT_INCREMENT = 'PLAYERS_COUNT_INCREMENT';
const PLAYERS_COUNT_DECREMENT = 'PLAYERS_COUNT_DECREMENT';
const UPDATE_PLAYERS_LIST = 'UPDATE_PLAYERS_LIST';
const INITIALIZE_PLAYERS_LIST = 'INITIALIZE_PLAYERS_LIST';

const UPDATE_QUEUE_LIST = 'UPDATE_QUEUE_LIST';
const RETURN_PLAYER_TO_LOBBY = 'RETURN_PLAYER_TO_LOBBY';
const MOVE_PLAYER_TO_TEAM = 'MOVE_PLAYER_TO_TEAM';
const QUEUE_COUNT_INCREMENT = 'QUEUE_COUNT_INCREMENT';
const QUEUE_COUNT_DECREMENT = 'QUEUE_COUNT_DECREMENT';


export {
  LOADING,
  TOGGLE_MODAL,
  UPDATE_TEAM_SETTINGS,
  PLAYERS_COUNT_INCREMENT,
  PLAYERS_COUNT_DECREMENT,
  UPDATE_PLAYERS_LIST,
  INITIALIZE_PLAYERS_LIST
  UPDATE_QUEUE_LIST,
  RETURN_PLAYER_TO_LOBBY,
  MOVE_PLAYER_TO_TEAM,
  QUEUE_COUNT_DECREMENT,
  QUEUE_COUNT_INCREMENT
};
