

const LOADING = 'LOADING';
const TOGGLE_MODAL = 'TOGGLE_MODAL';
const UPDATE_TEAM_SETTINGS = 'UPDATE_TEAM_SETTINGS';

const INITIALIZE_PLAYERS_LIST = 'INITIALIZE_PLAYERS_LIST';
const ADD_PLAYER_TO_LOBBY = 'ADD_PLAYER_TO_LOBBY';
const REMOVE_PLAYER_FROM_LOBBY = 'REMOVE_PLAYER_FROM_LOBBY';

const ADD_PLAYER_TO_QUEUE = 'ADD_PLAYER_TO_QUEUE';
const REMOVE_PLAYER_FROM_QUEUE = 'REMOVE_PLAYER_FROM_QUEUE';
const MOVE_PLAYER_TO_TEAM = 'MOVE_PLAYER_TO_TEAM';

const FILL_TEAM_FROM_QUEUE = 'FILL_TEAM_FROM_QUEUE';


export {
  LOADING,
  TOGGLE_MODAL,
  UPDATE_TEAM_SETTINGS,
  INITIALIZE_PLAYERS_LIST,
  ADD_PLAYER_TO_LOBBY,
  REMOVE_PLAYER_FROM_LOBBY,
  REMOVE_PLAYER_FROM_QUEUE,
  MOVE_PLAYER_TO_TEAM,
  ADD_PLAYER_TO_QUEUE
};
